# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'sebastianodimartina'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: Progetti
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: Articoli
    link: /
  - name: Tags
    link: /tags
  - name: Chi sono
    link: /chi-sono
  - name: Seguimi 
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/sebadima
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/sebastiano-dimartina-2005879/
      - name: Twitter
        icon: twitter
        link: https://twitter.com/sebadima
    
